name: Continuous Integration
'on':
- push
- pull_request_target
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "event commit $GITHUB_REF/${GITHUB_SHA}"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout PR HEAD
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: 'sudo apt-get install wget build-essential libgflags-dev libgoogle-glog-dev
        clang-format-3.9 libzmq3-dev -y

        '
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: 3.16.x
    - name: Setup GTest
      run: '# gtest

        mkdir tmp

        cd tmp

        wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz

        tar -xf release-1.8.0.tar.gz

        cd googletest-release-1.8.0

        mkdir build

        cd build

        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_GTEST=1 -DBUILD_GMOCK=0 ..

        sudo make install -j8

        cd ../..

        '
    - name: Setup CPPZMQ
      run: '# cppzmq

        git clone https://github.com/zeromq/cppzmq

        cd cppzmq

        git checkout tags/v4.6.0

        cd ..

        sudo cp cppzmq/zmq.hpp /usr/local/include

        sudo cp cppzmq/zmq_addon.hpp /usr/local/include

        '
    - name: Check clang-format
      run: ${{github.workspace}}/scripts/clang-format.py
      shell: bash
    - name: CppLint
      run: if [[ $(${{github.workspace}}/scripts/lint.py | grep "Total errors found.")
        == 0 ]]; then exit 1; else exit 0; fi
      shell: bash
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Unit Tests
      working-directory: ${{github.workspace}}/build/tests
      shell: bash
      run: ./circinus_unit_tests
    - name: Test algorithms
      working-directory: ${{github.workspace}}/build/tests
      shell: bash
      run: ./TestVertexCover
